export const achievementsSeed = [
  { slug: "first-steps", name: "First Steps", description: "Complete your first lesson", xpReward: 25, icon: "Sparkles", category: "milestone", condition: JSON.stringify({ type: "sessions_completed", threshold: 1 }) },
  { slug: "week-warrior", name: "Week Warrior", description: "Maintain a 7-day study streak", xpReward: 100, icon: "Flame", category: "streak", condition: JSON.stringify({ type: "streak", threshold: 7 }) },
  { slug: "month-master", name: "Month Master", description: "Maintain a 30-day study streak", xpReward: 300, icon: "Calendar", category: "streak", condition: JSON.stringify({ type: "streak", threshold: 30 }) },
  { slug: "vocab-100", name: "Word Collector", description: "Master 100 vocabulary words", xpReward: 50, icon: "BookOpen", category: "volume", condition: JSON.stringify({ type: "vocab_mastered", threshold: 100 }) },
  { slug: "vocab-500", name: "Vocabulary Master", description: "Master 500 vocabulary words", xpReward: 150, icon: "BookOpen", category: "volume", condition: JSON.stringify({ type: "vocab_mastered", threshold: 500 }) },
  { slug: "kanji-50", name: "Kanji Beginner", description: "Learn 50 kanji characters", xpReward: 50, icon: "Languages", category: "volume", condition: JSON.stringify({ type: "kanji_learned", threshold: 50 }) },
  { slug: "kanji-200", name: "Kanji Climber", description: "Learn 200 kanji characters", xpReward: 150, icon: "Mountain", category: "volume", condition: JSON.stringify({ type: "kanji_learned", threshold: 200 }) },
  { slug: "perfect-quiz", name: "Perfect Score", description: "Score 100% on a practice quiz", xpReward: 50, icon: "Trophy", category: "accuracy", condition: JSON.stringify({ type: "perfect_quiz", threshold: 1 }) },
  { slug: "perfect-exam", name: "Exam Ace", description: "Score 100% on a mock exam", xpReward: 200, icon: "Trophy", category: "accuracy", condition: JSON.stringify({ type: "perfect_exam", threshold: 1 }) },
  { slug: "accuracy-80", name: "Sharp Mind", description: "Maintain 80% average accuracy", xpReward: 75, icon: "Target", category: "accuracy", condition: JSON.stringify({ type: "avg_accuracy", threshold: 80 }) },
  { slug: "accuracy-90", name: "Precision Master", description: "Maintain 90% average accuracy", xpReward: 150, icon: "Target", category: "accuracy", condition: JSON.stringify({ type: "avg_accuracy", threshold: 90 }) },
  { slug: "night-owl", name: "Night Owl", description: "Study after midnight 10 times", xpReward: 50, icon: "Moon", category: "milestone", condition: JSON.stringify({ type: "late_study", threshold: 10 }) },
  { slug: "early-bird", name: "Early Bird", description: "Study before 7 AM 10 times", xpReward: 50, icon: "Sun", category: "milestone", condition: JSON.stringify({ type: "early_study", threshold: 10 }) },
  { slug: "ai-explorer", name: "AI Explorer", description: "Have 10 AI Tutor conversations", xpReward: 50, icon: "Bot", category: "milestone", condition: JSON.stringify({ type: "ai_sessions", threshold: 10 }) },
  { slug: "flashcard-100", name: "Card Shark", description: "Review 100 flashcards", xpReward: 50, icon: "Layers", category: "volume", condition: JSON.stringify({ type: "flashcards_reviewed", threshold: 100 }) },
  { slug: "flashcard-500", name: "Memory Palace", description: "Review 500 flashcards", xpReward: 150, icon: "Layers", category: "volume", condition: JSON.stringify({ type: "flashcards_reviewed", threshold: 500 }) },
  { slug: "n5-ready", name: "N5 Scholar", description: "Reach 80% readiness for JLPT N5", xpReward: 200, icon: "GraduationCap", category: "milestone", condition: JSON.stringify({ type: "level_readiness", threshold: 80, level: "n5" }) },
  { slug: "n4-ready", name: "N4 Scholar", description: "Reach 80% readiness for JLPT N4", xpReward: 300, icon: "GraduationCap", category: "milestone", condition: JSON.stringify({ type: "level_readiness", threshold: 80, level: "n4" }) },
  { slug: "polyglot-path", name: "Polyglot Path", description: "Study both JLPT and TOEFL", xpReward: 100, icon: "Globe", category: "milestone", condition: JSON.stringify({ type: "dual_subject", threshold: 1 }) },
  { slug: "daily-challenger", name: "Daily Challenger", description: "Complete 7 daily challenges", xpReward: 100, icon: "Zap", category: "volume", condition: JSON.stringify({ type: "daily_challenges", threshold: 7 }) },
];
